### ISSUE TITLE
Trying to modify hsdev.py to only inspect when haskell project is open

### ISSUE THREAD

**Issue by jaxuru** [SublimeHaskell/SublimeHaskell#276] opened 2016-08-03 17:53 UTC
I'm trying to pick through the SublimeHaskell code to write an edit for a pull request, I'm trying to get it so that the high-usage database inspection only happens when a .hs file is open. I'm fairly lost in sublime plugin development, so I'm wondering if anybody would also want that feature and knows a bit more about writing plugins. It's annoying to have the usage spike as it inspects the databases when I'm just trying to write a quick note or bash script in Sublime Text.

Here is my attempt:
https://github.com/jaxuru/SublimeHaskell/commit/84c4c19e97405ed334392ce3b2fba9ed1744c941#diff-0fcb66af0acfba9915188b164f2005a3

Here is an example of a plugin that only activates when its relevant files are open:
https://github.com/OmniSharp/omnisharp-sublime

Also, even better than when .hs files are open is if it could check for a .cabal file in the project before inspecting the files.

**Comment by mvoidex** [comment] 2016-08-08 16:00
Good idea! I'll review code when I'll have some time (maybe this weekend).

**Comment by bscottm** [comment] 2017-03-02 17:29
@jaxuru, @mvoidex : This is a duplicate of issue 274.

**Comment by bscottm** [comment] 2017-09-26 05:13
@jaxuru: Should no longer be an issue. Re-open if necessary.

**Closed by bscottm** 2017-09-26 05:13 UTC
Labels: duplicate
