### ISSUE TITLE
build seems to hang

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#308] opened 2017-03-10 20:38 UTC
on commit 3d2753568a28260dd329822d4deb6d4b1ec63444 in my repo 
https://github.com/cartazio/libressl-hs (that commit is the current tip of the WIP branch)
when i'm using new-build as my build command, on OSX,

sublime haskell hangs instead of giving me the type errors, but the command line execution works fine. 

I had a similar issue with vanilla build before, but this seems to be more of the same, 
the way I was using new-build was by replacing the source python that had the 'build' command strings with 'new-build' in the file that tracks such stuff

**Comment by cartazio** [comment] 2017-03-10 20:39
may or may not have to do with not doing a 'new-configure' before hand, but i dont think so ...

**Comment by cartazio** [comment] 2017-03-12 14:01
definitely seeing that recent sublime is hanging / not terminating subprocess calls properly with new build on errors now ...

**Comment by mvoidex** [comment] 2017-03-12 20:24
Hi, i'll try to get into next weekend

**Comment by cartazio** [comment] 2017-03-12 23:01
If I forget, please as me to post my new build edits so you can reproduce
it.

I can also make links to my binaries and config available

**Comment by bscottm** [comment] 2017-03-13 17:15
If you build from the command line/terminal window, do you have a lot of error output?

**Comment by bscottm** [comment] 2017-03-14 05:12
@cartazio: If you're willing to try to test using the `git` version, here's how:

- Uninstall the SublimeHaskell plugin (`PackageManager: Remove package`)
- Then use `git` to manually install the plugin:

```shell
    pushd "~/Library/Application Support/Sublime Text 3/Packages"
    git clone https://github.com/bscottm/SublimeHaskell.git
    cd SublimeHaskell
    git checkout reactive_output
    popd
```

The branch's name is `reactive_output`. You can get back to the `master` branch (the current release version):

```shell
    pushd "~/Library/Application Support/Sublime Text 3/Packages"
    git checkout master
    popd
```

You can also completely remove the directory and use `Package Manager` to re-install the released plugin.

**Comment by bscottm** [comment] 2017-03-15 18:43
@cartazio: I will push a new version of SublimeHaskell with a possible fix to this issue later today (Pacific TZ, US). However, I will need you to verify that this issue is fixed... (silence is tacit consent after a week, and then I close the issue... :-)

**Comment by cartazio** [comment] 2017-03-15 19:20
i'm a teeny bit hosed this week... need to do some crypto proofs for work
on a commercial time scale :''-o

**Comment by cartazio** [comment] 2017-03-15 19:46
oh, let me know when the new version is up and i'll test it out :)

**Comment by cartazio** [comment] 2017-03-15 19:47
(didn't read closely enough to see that I'd need only restart sublime to pickup the candidate fix)

**Comment by bscottm** [comment] 2017-03-15 22:09
@cartazio: New version of plugin merged. Let me know if this fixes the issue (preferably in the next week or so, if you can.)

**Comment by cartazio** [comment] 2017-03-18 16:18
now i just get exit code 0 vs 1, but no output from stderror  or wherever ghc / cabal emits simple things like 

```
Preprocessing library numerical-0.1.0.0...
[15 of 21] Compiling Numerical.Array.Layout.Base ( src/Numerical/Array/Layout/Base.hs, /Users/carter/WorkSpace/projects/active/WellPosedWork/code/numerical/dist-newstyle/build/numerical-0.1.0.0/build/Numerical/Array/Layout/Base.o )

src/Numerical/Array/Layout/Base.hs:122:47: error:
    • Variable not in scope:
        majorCompareRightToLeft :: Ordering -> Ordering -> Ordering
    • Perhaps you meant ‘shapeCompareRightToLeft’ (line 122)
```

added that error to test it out, seems like youre dropping something, at least when using new build check out #313 to see how i shim in new build

**Comment by cartazio** [comment] 2017-03-18 16:26
for context my sublime hs user config is 

```
{
	"add_to_PATH":
	[ "/Users/carter/bin",
		"/Users/carter/.cabal/bin",
    "/Users/carter/.install-ghc/ghc-8.0.2/bin",
    "/usr/local/bin/"

	],
	"auto_build_mode": "normal",
  // "auto_build_mode": "normal-then-warnings",
	"enable_auto_build": true,
    // Show output window on clean/configure/build/install:
  "show_output_window": true,

  // Show error window on build/check/lint:
  "show_error_window": true,

  "auto_run_tests": false,
	"enable_auto_lint": false,
  "enable_auto_check": false,
	"enable_ghc_mod": false,
	"enable_hdevtools": false,
	"enable_hsdev": false,
	"inspect_modules": false,
  "haskell_build_tool": "cabal"
}
```


for example, if you were to clone my numerical haskell repo at the current tip commit on master,
https://github.com/wellposed/numerical/commit/ed0471d25c051d6821f70726df8fad9cabb87260
cabal new-build reports the following warnings, none of which show up in sublime haskell! (even when i wipe out the dist directory!)

**Comment by cartazio** [comment] 2017-03-18 16:28
(or dist-newstyle directory)

either way, this is more of a regression cause i dont even get the warnings at the end, just the cli exit codes :(

**Comment by cartazio** [comment] 2017-03-18 16:29
@bscottm appreciate your patience ... and i hope im being moderately informative.

**Comment by bscottm** [comment] 2017-03-18 17:42
@cartazio: Two questions:

- There's an enhancement to `build.py` that you'd like me to integrate?
- How to reproduce the `numerical-0.1.0.0` issue? Compile using `cabal` as my build system? Can I sandbox?

**Comment by cartazio** [comment] 2017-03-18 19:21
do cabal new-build, or cabal build should work. i can confirm that both
cabal build and new-build show lots of warnings on CLI, and at least when i
do my slightly tweaked version using new-build instead of build wrt my
build.py file theres no warnings output

the enhancement is something i'm more than happy to just by hand edit back
into my sublime haskell instance locally while cabal new-build is immature.
the write interface piece  (or something like that) might be needed so that
case coverage checking to work in the -fno-code path (or maybe its hosed no
matter what)

**Comment by bscottm** [comment] 2017-03-18 23:48
@cartazio: Ok, if I understand you correctly, there's missing output if I `cabal build`. I can track that down. 8.0.1 or 7.10.3?

**Comment by bscottm** [comment] 2017-03-18 23:49
@cartazio: At least the build doesn't hang. :-)

**Comment by cartazio** [comment] 2017-03-20 01:17
I'm on 8.0.2 but should be the same in any of them.

The build would never hang, merely sublime ui

Make sure you're on up to date cabal install.  I'm on OS X 10.12

Maybe the error reporting is on stderr and you need to track both stdout
and stderr, and then something with that?  I have no clue what I'm talking
about. :)

**Comment by bscottm** [comment] 2017-03-20 22:08
@cartazio: Vexing. I'm trying to multiplex `stdout` and `stderr` output to the build window. I'm probably getting too clever by a half.

**Comment by bscottm** [comment] 2017-03-21 05:16
@cartazio: Found the problem. Need to test more before pushing update.

**Comment by cartazio** [comment] 2017-03-21 17:11
yay! care to share what happened?

**Comment by mvoidex** [comment] 2017-03-21 20:08
@bscottm, sorry for delay, i'll look into your branch in few days

**Comment by cartazio** [comment] 2017-03-21 21:50
any ways i can test/validate/by hand patch for now till the next time i restart sublime ;)?

**Comment by bscottm** [comment] 2017-03-21 23:08
@cartazio: Unicode string foo and universal newlines in subprocess.Popen.

**Comment by bscottm** [comment] 2017-03-23 00:28
@cartazio: Sorry about the interminable pause... no pun intended. The branch name in my repo (bscottm/SublimeHaskell) is `reactive_output`.

**Comment by bscottm** [comment] 2017-03-23 00:28
@cartazio: And I'm still doing testing. Mac OS X is later this evening.

**Comment by bscottm** [comment] 2017-03-23 04:07
@cartazio: SublimeHaskell master updated. Update plugin, issue SBF.

**Comment by cartazio** [comment] 2017-03-23 12:29
Ok:

1) i get the warnings now

2) build on file save seems to no longer work (or maybe its clever and just ignores `	"enable_auto_build": true,` in the sublime haskell user file config)? so i'm having to select the build command on the command pallet

3) doesn't seem to highlight the warnings sites, but that perhaps should be an option setting?

**Comment by cartazio** [comment] 2017-03-23 12:31
so progress but regressions :)

**Comment by bscottm** [comment] 2017-03-23 22:43
@cartazio: Going once...

**Comment by cartazio** [comment] 2017-03-24 03:22
Works for me afaict

**Comment by bscottm** [comment] 2017-03-24 03:49
Feel free to re-open if necessary.

**Closed by bscottm** 2017-03-24 03:49 UTC
