### ISSUE TITLE
enable_hsdev : false ignored in settings warnings

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#332] opened 2017-04-29 20:04 UTC
```
It's used in most features of SublimeHaskell
Check if it's installed and in PATH
If it's not installed, run 'cabal install hsdev' to install hsdev
You may also want to adjust 'add_to_PATH' setting

To supress this message and disable hsdev set 'enable_hsdev' to false
```

i definitely have enable_hsdev set to false...
also pretty sure that the subprocess call for invoking ghc or whatever isn't inheriting the right parent PATH / add_to_path logic ...

**Comment by bscottm** [comment] 2017-05-01 17:49
@cartazio: SBF in 1.2.4, previously noted. The backend logic definitely needs refactoring based on what the plugin finds -- no `hsdev`, fallback to `ghc-mod`. No `ghc-mod`, give up (because who really uses `hdevtools`?)

**Comment by Pastafarianist** [comment] 2017-08-15 10:06
This problem is still relevant as of the latest version.

**Comment by Pastafarianist** [comment] 2017-08-15 10:07
Duplicate of https://github.com/SublimeHaskell/SublimeHaskell/issues/336.

**Comment by bscottm** [comment] 2017-09-26 05:23
@cartazio: No longer an issue. `enable_hsdev` is no longer an option in 2.0.0.

**Closed by bscottm** 2017-09-26 05:23 UTC
