### ISSUE TITLE
hsdev IO exception in stack-based project

### ISSUE THREAD

**Issue by iamrecursion** [SublimeHaskell/SublimeHaskell#298] opened 2017-01-30 21:25 UTC
I'm seeing errors akin to this every time that SublimeHaskell attempts to call to hsdev. 

`
Sublime Haskell: hsdev check returns error: ghc error, id: 4, msg: io exception: readCreateProcess: <snip>\AppData\Roaming\local\bin\stack.exe "path" "--compiler" "ghc-8.0.1" "--arch" "x86_64" (exit 1): failed
`

This error occurs for `hsdev check`, `hsdev types` and `hsdev complete` with the same message. It only occurs inside a stack project, as I cannot reproduce it with a bare file, getting the completions, linting and other behaviour as expected. 

Manually running the command to stack printed in the error for me produces a significant amount of output, and I don't know what hsdev is expecting back.

**Comment by mvoidex** [comment] 2017-01-30 21:27
Can you try running this:

    stack.exe path --compiler ghc-8.0.1 --arch x86_64

within you stack project?

**Comment by iamrecursion** [comment] 2017-01-30 21:41
That produces the significant amount of output as mentioned before. Please find it below, with any identifying paths snipped. 

```
stack-root: C:\sr
project-root: C:\Users\<user>\<project path>
config-location: C:\Users\<user>\<project path>\stack.yaml
bin-path: C:\sr\snapshots\22b390ad\bin;C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin;C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\mingw\bin;C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin;C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\usr\bin;C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\usr\local\bin;C:\Program Files\Haskell\bin;C:\Development\haskell_platform\8.0.2\lib\extralibs\bin;C:\Development\haskell_platform\8.0.2\bin;C:\Development\python3\Scripts\;C:\Development\python3\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Development\Perl5\c\bin;C:\Development\Perl5\perl\site\bin;C:\Development\Perl5\perl\bin;C:\Program Files (x86)\GnuPG\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Development\LLVM\bin;C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;C:\Users\<user>\AppData\Roaming\cabal\bin;C:\Development\haskell_platform\8.0.1\msys\usr\bin;C:\Development\rust\bin;C:\Development\java\jdk\bin;C:\Program Files (x86)\Pandoc\;C:\Development\MATLAB\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Development\haskell_platform\8.0.2\mingw\bin;C:\Users\<user>\AppData\Roaming\local\bin;C:\Users\<user>\AppData\Local\atom\bin;C:\Development\MiKTeX\miktex\bin\x64\;C:\Users\<user>\AppData\Local\Microsoft\WindowsApps;C:\Users\<user>\.cargo\bin
programs: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows
compiler-exe: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.exe
compiler-bin: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin
local-bin: C:\Users\<user>\AppData\Roaming\local\bin
extra-include-dirs: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include
extra-library-dirs: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
snapshot-pkg-db: C:\sr\snapshots\22b390ad\pkgdb
local-pkg-db: C:\Users\<user>\<project path>\.stack-work\install\9e493ef9\pkgdb
global-pkg-db: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\lib\package.conf.d
ghc-package-path: C:\Users\<user>\<project path>\.stack-work\install\9e493ef9\pkgdb;C:\sr\snapshots\22b390ad\pkgdb;C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\lib\package.conf.d
snapshot-install-root: C:\sr\snapshots\22b390ad
local-install-root: C:\Users\<user>\<project path>\.stack-work\install\9e493ef9
snapshot-doc-root: C:\sr\snapshots\22b390ad\doc
local-doc-root: C:\Users\<user>\<project path>\.stack-work\install\9e493ef9\doc
dist-dir: .stack-work\dist\b7fec021
local-hpc-root: C:\Users\<user>\<project path>\.stack-work\install\9e493ef9\hpc
local-bin-path: C:\Users\<user>\AppData\Roaming\local\bin
ghc-paths: C:\Users\<user>\AppData\Local\Programs\stack\x86_64-windows
```

**Comment by mvoidex** [comment] 2017-01-30 21:51
Ah, I see.
This is valid output, but hsdev says, that stack exits with error code 1 (`(exit 1)`).

Try run same exactly this command from ghci:

    > import System.Directory
    > import System.Process
    > setCurrentDirectory "your stack directory"
    > (exitCode, out, err) <- readProcessWithExitCode "<snip>\AppData\Roaming\local\bin\stack.exe" ["path", "--compiler", "ghc-8.0.1", "--arch", "x86_64"] ""
    > print exitCode

Can you also look into hsdev's log at `C:\Users\<user>\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev\hsdev.log`? There may be some additional info

p.s. i am at UTC+3, here's 1 am now, so i can look into tommorow when i have some time

**Comment by iamrecursion** [comment] 2017-01-30 22:25
I've run those commands from the ghci instance provided by `stack ghci`, and also calling ghci on the system path. I assumed that when you said "your stack directory" you were referring to the project directory.

Running from the system ghci I get:
```
λ > print exitCode
ExitSuccess
it :: ()
```

Running from ghci within the stack project gives the same result:
```
λ > print exitCode
ExitSuccess
it :: ()
```

Looking in the hsdev log, the only things I can see are some IO Exceptions while reading from / writing to the cache file. The log is very full of file-paths with identifying information in, so if you have specific things that you're thinking of I'm happy to remove that information from the paths.

**Comment by iamrecursion** [comment] 2017-01-30 22:30
Looking through the Sublime console I've also spotted this

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\commands.py", line 104, in on_query_context
    return can_complete_qualified_symbol(get_qualified_symbol(preline))
NameError: global name 'can_complete_qualified_symbol' is not defined
```

**Comment by mvoidex** [comment] 2017-01-31 09:10
> The log is very full of file-paths with identifying information in, so if you have specific things that you're thinking of I'm happy to remove that information from the paths.

Search for `AppData\Roaming\local\bin\stack.exe` invocation, or `readCreateProcess`. There should be error with same message as SublimeHaskell shows. Or you can just upload log somewhere, I'll take a look.
(you can also delete it, and reproduce bug again, so that log will be smaller)

> Looking through the Sublime console I've also spotted this:

Seems, that your SublimeHaskell plugin is not updated. There's issue for it: https://github.com/SublimeHaskell/SublimeHaskell/issues/289
It should be fixed now

**Comment by iamrecursion** [comment] 2017-01-31 22:24
> Seems, that your SublimeHaskell plugin is not updated. There's issue for it: #289
> It should be fixed now

That's odd! It seems my Package Control has been failing to keep plugins up to date. Having updated I can no longer reproduce both issues. I will let you know if either of them re-emerge. 

I'm sorry for not checking the plugin version beforehand. I'd assumed that Package Control was operating properly.

**Comment by mvoidex** [comment] 2017-01-31 22:28
no problem

**Comment by mvoidex** [comment] 2017-02-04 21:16
I'll close issue, feel free to reopen if issue reappear

**Closed by mvoidex** 2017-02-04 21:16 UTC

**Comment by iamrecursion** [comment] 2017-02-07 21:31
I'm not sure if it's related, but on a different system (with an identical setup as far as I can tell) I'm seeing IO Exceptions as follows `Scope leaves with exception: C:\Development\haskell_platform\8.0.1\lib\settings: openFile: does not exist (No such file or directory)`.

As far as Package Control is concerned, SublimeHaskell is up to date, as is hsdev. 

Please find the hsdev log here: [hsdev.txt](https://github.com/SublimeHaskell/SublimeHaskell/files/759020/hsdev.txt).

While it may not be related, I am also seeing the following error in the Sublime Console, coming from SublimeHaskell's side:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 557, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "C:\Users\<USER>\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\commands.py", line 104, in on_query_context
    return autocomplete.can_complete_qualified_symbol(get_qualified_symbol(preline))
  File "C:\Users\<USER>\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\autocomplete.py", line 369, in can_complete_qualified_symbol
    return list(filter(lambda m: m.startswith(info.module), autocompletion.get_current_module_completions())) != []
  File "C:\Users\<USER>\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev.py", line 1144, in wrapped
    return fn(*args, **kwargs)
  File "C:\Users\<USER>\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\autocomplete.py", line 343, in get_current_module_completions
    return set([m.name for m in hsdev.client.scope_modules(self.current_filename)])
TypeError: 'NoneType' object is not iterable
```

**Comment by mvoidex** [comment] 2017-02-07 21:47
> `C:\Development\haskell_platform\8.0.1\lib\settings: openFile: does not exist (No such file or directory)`

Haven't you moved your ghc by hand from one folder to another? Or just installed new ghc and removed old one?
This may be when `hsdev` was built with `ghc` installed in `C:\Development\haskell_platform\8.0.1`, but now it seems to be gone.
`hsdev` uses `libdir` from `ghc-paths` package, which is hardcoded unfortunately. I.e. if you build `hsdev` with `ghc` from `C:\ghc`, it will use only this folder for ghc initialization.

Related issue: https://github.com/mvoidex/hsdev/issues/44

**Comment by iamrecursion** [comment] 2017-02-08 15:52
Ah, that was the initial issue! I didn't realise that I needed to rebuild hsdev on changing my Haskell Platform version. 

Fixing that, however, has allowed me to reproduce the initial error that this Issue has been concerning: `hsdev scope modules returns error: io error, id: 5, msg: readCreateProcess: C:\Users\<USER>\AppData\Roaming\local\bin\stack.exe "path" "--compiler" "ghc-8.0.1" "--arch" "x86_64" (exit 1): failed`. This occurs in addition to the traceback [here](https://github.com/SublimeHaskell/SublimeHaskell/issues/298#issuecomment-278146579).

Please find the log from hsdev attached [here](https://github.com/SublimeHaskell/SublimeHaskell/files/761129/hsdev.txt).
